package nl.tvdven.ligatum.core.command.agent;

public class Command {

    public String help() {

        String help = String.join("Usage: serf agent [options]"
        ,""
        ,"  Starts the Serf agent and runs until an interrupt is received. The"
        ,"  agent represents a single node in a cluster."
        ,""
        ,"Options:"
        ,""
        ,"  -bind=0.0.0.0:7946       Address to bind network listeners to. To use an IPv6"
        ,"                           address, specify [::1] or [::1]:7946."
        ,"  -iface                   Network interface to bind to. Can be used instead of"
        ,"                           -bind if the interface is known but not the address."
        ,"                           If both are provided, then Serf verifies that the"
        ,"                           interface has the bind address that is provided. This"
        ,"                           flag also sets the multicast device used for -discover."
        ,"  -advertise=0.0.0.0       Address to advertise to the other cluster members"
        ,"  -config-file=foo         Path to a JSON file to read configuration from."
        ,"                           This can be specified multiple times."
        ,"  -config-dir=foo          Path to a directory to read configuration files"
        ,"                           from. This will read every file ending in \".json\""
        ,"                           as configuration in this directory in alphabetical"
        ,"                           order."
        ,"  -discover=cluster        A cluster name used to discovery peers. On"
        ,"                           networks that support multicast, this can be used to have"
        ,"                           peers join each other without an explicit join."
        ,"  -encrypt=foo             Key for encrypting network traffic within Serf."
        ,"                           Must be a base64-encoded 16-byte key."
        ,"  -keyring-file            The keyring file is used to store encryption keys used"
        ,"                           by Serf. As encryption keys are changed, the content of"
        ,"                           this file is updated so that the same keys may be used"
        ,"                           during later agent starts."
        ,"  -event-handler=foo       Script to execute when events occur. This can"
        ,"                           be specified multiple times. See the event scripts"
        ,"                           section below for more info."
        ,"  -join=addr               An initial agent to join with. This flag can be"
        ,"                           specified multiple times."
        ,"  -log-level=info          Log level of the agent."
        ,"  -node=hostname           Name of this node. Must be unique in the cluster"
        ,"  -profile=[lan|wan|local] Profile is used to control the timing profiles used in Serf."
        ,"                           The default if not provided is lan."
        ,"  -protocol=n              Serf protocol version to use. This defaults to"
        ,"                           the latest version, but can be set back for upgrades."
        ,"  -rejoin                  Ignores a previous leave and attempts to rejoin the cluster."
        ,"                           Only works if provided along with a snapshot file."
        ,"  -retry-join=addr         An agent to join with. This flag be specified multiple times."
        ,"                           Does not exit on failure like -join, used to retry until success."
        ,"  -retry-interval=30s      Sets the interval on which a node will attempt to retry joining"
        ,"                           nodes provided by -retry-join. Defaults to 30s."
        ,"  -retry-max=0             Limits the number of retry events. Defaults to 0 for unlimited."
        ,"  -role=foo                The role of this node, if any. This can be used"
        ,"                           by event scripts to differentiate different types"
        ,"                           of nodes that may be part of the same cluster."
        ,"                           '-role' is deprecated in favor of '-tag role=foo'."
        ,"  -rpc-addr=127.0.0.1:7373 Address to bind the RPC listener."
        ,"  -snapshot=path/to/file   The snapshot file is used to store alive nodes and"
        ,"                           event information so that Serf can rejoin a cluster"
        ,"                           and avoid event replay on restart."
        ,"  -tag key=value           Tag can be specified multiple times to attach multiple"
        ,"                           key/value tag pairs to the given node."
        ,"  -tags-file=/path/to/file The tags file is used to persist tag data. As an agent's"
        ,"                           tags are changed, the tags file will be updated. Tags"
        ,"                           can be reloaded during later agent starts. This option"
        ,"                           is incompatible with the '-tag' option and requires there"
        ,"                           be no tags in the agent configuration file, if given."
        ,"  -syslog                  When provided, logs will also be sent to syslog."
        ,"  -broadcast-timeout=5s    Sets the broadcast timeout, which is the max time allowed for"
        ,"                           responses to events including leave and force remove messages."
        ,"                           Defaults to 5s."
        ,""
        ,"Event handlers:"
        ,""
        ,"  For more information on what event handlers are, please read the"
        ,"  Serf documentation. This section will document how to configure them"
        ,"  on the command-line. There are three methods of specifying an event"
        ,"  handler:"
        ,""
        ,"- The value can be a plain script, such as \"event.sh\". In this case,"
        ,"  Serf will send all events to this script, and you'll be responsible"
        ,"  for differentiating between them based on the SERF_EVENT."
        ,""
        ,"- The value can be in the format of \"TYPE=SCRIPT\", such as"
        ,"  \"member-join=join.sh\". With this format, Serf will only send events"
        ,"  of that type to that script."
        ,""
        ,"- The value can be in the format of \"user:EVENT=SCRIPT\", such as"
        ,"  \"user:deploy=deploy.sh\". This means that Serf will only invoke this"
        ,"  script in the case of user events named \"deploy\"."
        );

        return help;
    }
}
